highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: 
title: Leonardo Barboza (lnrd@hotmail.com) Infraestrutura - Segurança da Informação - Sysadmin
name: Leonardo Barboza
email: lnrd@hotmail.com
email_full: mailto:lnrd@hotmail.com
website: linkr.bio/linux
website_full: https://linkr.bio/linux
github: lnrdlnx
linkedin: leonardobarboza/?locale=pt_BR
tel: +55 61 985505994
tel_full: tel:+5561985505994
google_maps: 'https://www.google.com.br/maps/place/+Brazil,+Brasilia'
address:
  city: Brasília
  country: Brazil
# google_analytics: G-3Q3RJ5P3W2

# needed for travis-ci build
# exclude: [vendor]